# demonstrating ssl issue and renewal with nginx and certbot

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/https-ssl-issuance.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    restart: always
    ports:
      - "80:80"
      - "443:443"
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
