# demonstrating https serving with certificate issuance and renewal with dedicated external database
# for production: copy this file and edit the DB params accordingly

services:
  moodle:
    container_name: moodle
    build:
      context: ./moodle
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=moodle
      - DB_USER=user
      - DB_PASSWORD=password
      - WWW_ROOT=https://example.com
    volumes:
      - moodle_source:/var/www/html/moodle
      - ./moodle-data:/home/moodle-data:rw
      - ./moodle_docker-fpm.ini:/usr/local/etc/php/conf.d/docker-fpm.ini:ro
      - ./moodle_config.php:/var/www/html/moodle/config.php:ro
      - ./moodle-plugins/mass_enroll:/var/www/html/moodle/local/mass_enroll:ro
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - moodle_source:/var/www/html/moodle
      - ./nginx/https.conf:/etc/nginx/conf.d/default.conf:ro
      - ./moodle-data:/home/moodle-data:rw
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - moodle
  certbot:
    image: certbot/certbot:v3.0.1
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
volumes:
  moodle_source:
